### PR TITLE
implementation of a new option "MERGEHISTORYFILES"

### PR DESCRIPTION
**Pull request by fhh2626**
Conventionally, DRR generate a large number of small history files (e.g. *.timestep.grad). This may make GUI SFTP software (WinSCP, etc.) get stuck when opening the corresponding directory, if the internet is not sufficiently fast. To circumvent this issue, one may want to merge all the history file into a *.hist.grad file, like what Colvars does.

In the implementation, MERGEHISTORYFILES is only available when TEXTOUTPUT is on. Moreover, there will be only one (1-frame) .drrstate being generated with MERGEHISTORYFILES on. To avoid unlucky damage of the .drrstate file, a .another.drrstate file will also be generated.

### CODE REVIEW

**Comment by fhh2626** [comment]
This implementation works on your version of Plumed2. However, if I merged the latest version from plumed/plumed2,  plumed raised:

```
PLUMED: +++ PLUMED error
PLUMED: +++ message follows +++
PLUMED: This command expects a floating point type. Received a void instead
PLUMED: If you are sure your code is correct you can disable this check with export PLUMED_TYPESAFE_IGNORE=yes
PLUMED: In case this is necessary, please report an issue to developers of PLUMED and of the MD code
PLUMED: See also https://github.com/plumed/plumed2/pull/653
```

`export PLUMED_TYPESAFE_IGNORE=yes` addressed this issue. Still, I cannot even understand what causes this issue (my plumed string, drr, this PR, etc.). So I uploaded all the files necessary to reproduce the issue for you.

[WTM-eABF.zip](https://github.com/HanatoK/plumed2/files/7779326/WTM-eABF.zip)

**Comment by HanatoK** [comment]
Thanks! Did you have regtests for this option?

**Comment by HanatoK** [comment]
> Thanks! Did you have regtests for this option?

Never mind. I can add it quickly.

**Comment by HanatoK** [comment]
> This implementation works on your version of Plumed2. However, if I merged the latest version from plumed/plumed2, plumed raised:
> 
> ```
> PLUMED: +++ PLUMED error
> PLUMED: +++ message follows +++
> PLUMED: This command expects a floating point type. Received a void instead
> PLUMED: If you are sure your code is correct you can disable this check with export PLUMED_TYPESAFE_IGNORE=yes
> PLUMED: In case this is necessary, please report an issue to developers of PLUMED and of the MD code
> PLUMED: See also https://github.com/plumed/plumed2/pull/653
> ```
> 
> `export PLUMED_TYPESAFE_IGNORE=yes` addressed this issue. Still, I cannot even understand what causes this issue (my plumed string, drr, this PR, etc.). So I uploaded all the files necessary to reproduce the issue for you.
> 
> [WTM-eABF.zip](https://github.com/HanatoK/plumed2/files/7779326/WTM-eABF.zip)

This may be an issue of the openmm-plumed interface. I think we can ignore it for now.

**Review by HanatoK — APPROVED** [review]

**Pull request merged**
